# Import Dependency

In [2]:
import numpy as np

# Creating Numpy Array

In [3]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:
# scalar
arr = np.array(42)
print(arr)

42


In [6]:
# one-dimension array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# two-dimension array
arr = np.array([ [1, 2, 3],
                 [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# three-dimension array
arr = np.array([
                [[1, 2, 3], [4, 5, 6],
                [1, 2, 3], [4, 5, 6]
                ]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.arange(5, 9)

array([5, 6, 7, 8])

In [14]:
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [16]:
arr = np.array([ [1, 2, 3],
                 [4, 5, 6]])
np.empty_like(arr)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(5, k = 2) # np.eye는 offset을 setting 할 수 있음

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros(2)

array([0., 0.])

In [25]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.ones(2)

array([1., 1.])

In [27]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.full(3,7)

array([7, 7, 7])

In [33]:
np.full((4, 2), 4)

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [29]:
np.full(shape = 3, fill_value = 7)

array([7, 7, 7])

In [32]:
np.full(shape = (3, 3), fill_value = 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [31]:
np.array([7, 7, 7])

array([7, 7, 7])

In [34]:
arr = np.array([0, 1, 2, 3])
print(arr.dtype)

int64


In [36]:
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


# The Data Types of NumPy
- i: integer
- b: boolean
- u: unsigned integer
- f: float
- c: complext float
- m: timedelta
- M: datetime
- O: object
- S: string
- U: unicode string
- V: fixed chunk of memory for other type(void)

In [40]:
arr = np.array(['a', '2', '3'], dtype = 'i')

print(arr)
print(arr.dtype) # 'a' is not integer, integer type can use only number not string or character.

ValueError: invalid literal for int() with base 10: 'a'

In [41]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32
