In [1]:
import numpy as np

In [2]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)

print(data + ones)

[2 3]


In [3]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [4]:
data = np.array([1.0, 2.0])

print(data * 1.6)

[1.6 3.2]


In [5]:
print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0


In [6]:
np.trunc([-3.1666, 3.6667])

array([-3.,  3.])

In [7]:
np.around(3.1666, 2)

3.17

In [8]:
np.floor([-3.1666, 3.6667])

array([-4.,  3.])

In [9]:
np.ceil([-3.1666, 3.6667])

array([-3.,  4.])