In [3]:
import numpy as np

In [5]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                           [[0, 1, 2, 3],
                            [4, 5, 6 ,7]],
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [6]:
print(array_example.size)

24


In [7]:
print(array_example.shape)

(3, 2, 4)


In [8]:
a = np.arange(6)

b = a.reshape(3, 2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # The number of component is not adequate

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [19]:
# Task
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, -1)
print(newarr, 'size:', newarr.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] size: 12


In [22]:
arr = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [24]:
arr = arr =np.array(
                [[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

print(arr[1, -1])

10


In [25]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
