In [1]:
import numpy as np

# Task 1

In [3]:
np.full((3, 3), 55)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

# Task 2

In [12]:
np.eye(1, 10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

# Task 3

In [15]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Task 4

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Task 5

In [33]:
result = np.zeros((5, 5))
arange = np.arange(5)
for i in range(5):
    result[i] = (result[i] + arange)
    
result

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# Task 6

In [44]:
result = np.zeros((2, 3, 4))
sec_axis = np.full(4, 2)

for i in range(2):
    result[i][1] = result[i][1] + sec_axis

result

array([[[0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [0., 0., 0., 0.]]])

# Task 7

In [54]:
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newRow = np.array([2, 1, 8])

np.vstack((array, newRow))

array([[ 3,  2,  8],
       [ 4, 12, 34],
       [23, 12, 67],
       [ 2,  1,  8]])

# Task 8

In [62]:
A = np.ones(3) * 1
B = np.ones(3) * 2

first = np.add(A, B)
second = np.divide(-A, 2)
result = np.multiply(first, second)
result

array([-1.5, -1.5, -1.5])

# Task 9

In [65]:
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]

for i in list:
    print(np.mean(i))

5.5
30.6
34.0


# Task 10

In [73]:
def create_pattern_matrix(n):
    pattern_matrix = np.zeros((n, n), dtype=int)

    for i in range(n):
        for j in range(n):
            if i % 2 == 0:
                pattern_matrix[i][j] = 1 if j % 2 == 1 else 0
            else:
                pattern_matrix[i][j] = 1 if j % 2 == 0 else 0

    return pattern_matrix

n = 8
pattern_matrix = create_pattern_matrix(n)

print(pattern_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
