In [2]:
import torch
import numpy as np

In [3]:
x = torch.empty(5, 4)
x

tensor([[-3.7761e-12,  4.5747e-41, -3.7761e-12,  4.5747e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.8217e-44,  0.0000e+00,  2.6856e-34,  0.0000e+00],
        [ 1.5849e-42,  2.2405e-01,  0.0000e+00,  0.0000e+00],
        [ 1.8217e-44,  4.5747e-41,  2.6856e-34,  0.0000e+00]])

In [5]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(2, 2, 2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [7]:
torch.rand(5, 6)

tensor([[0.4310, 0.6596, 0.6259, 0.2063, 0.2186, 0.0876],
        [0.7717, 0.0236, 0.7535, 0.4206, 0.3215, 0.0959],
        [0.9998, 0.5275, 0.9737, 0.6481, 0.8803, 0.8318],
        [0.5243, 0.1548, 0.7529, 0.6391, 0.7816, 0.2934],
        [0.4036, 0.7785, 0.2118, 0.6019, 0.3464, 0.0323]])

In [9]:
l = [13, 4]
r = np.array([4, 56, 7])
torch.tensor(l)

tensor([13,  4])

In [10]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [11]:
x.size()[1]

4

In [12]:
x.size()[0]

5

In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [14]:
x + y

tensor([[1.0025, 0.4808],
        [0.3192, 1.1240]])

In [15]:
x - y

tensor([[-0.8029,  0.1997],
        [ 0.1274, -0.6249]])

In [16]:
x * y

tensor([[0.0901, 0.0478],
        [0.0214, 0.2182]])

In [17]:
x = torch.rand(8, 8)
x.size()

torch.Size([8, 8])

In [18]:
a = x.view(64)
a.size()

torch.Size([64])

In [19]:
a

tensor([0.7190, 0.3060, 0.0209, 0.2476, 0.1641, 0.2555, 0.1289, 0.8309, 0.6818,
        0.9371, 0.8548, 0.6727, 0.2647, 0.9919, 0.9099, 0.2022, 0.5495, 0.1873,
        0.9969, 0.8591, 0.9500, 0.1245, 0.8066, 0.0252, 0.6724, 0.5975, 0.7749,
        0.3197, 0.0088, 0.9026, 0.9393, 0.6105, 0.9201, 0.5216, 0.9063, 0.1827,
        0.2246, 0.6615, 0.7207, 0.9002, 0.5848, 0.5429, 0.5772, 0.8096, 0.6605,
        0.6343, 0.1809, 0.7287, 0.8958, 0.2787, 0.7523, 0.8852, 0.4710, 0.6392,
        0.1260, 0.9431, 0.7909, 0.7231, 0.5006, 0.5039, 0.4290, 0.1759, 0.4063,
        0.9533])

In [20]:
b = x.view(-1, 4, 4)
b.size()

torch.Size([4, 4, 4])

In [21]:
b

tensor([[[0.7190, 0.3060, 0.0209, 0.2476],
         [0.1641, 0.2555, 0.1289, 0.8309],
         [0.6818, 0.9371, 0.8548, 0.6727],
         [0.2647, 0.9919, 0.9099, 0.2022]],

        [[0.5495, 0.1873, 0.9969, 0.8591],
         [0.9500, 0.1245, 0.8066, 0.0252],
         [0.6724, 0.5975, 0.7749, 0.3197],
         [0.0088, 0.9026, 0.9393, 0.6105]],

        [[0.9201, 0.5216, 0.9063, 0.1827],
         [0.2246, 0.6615, 0.7207, 0.9002],
         [0.5848, 0.5429, 0.5772, 0.8096],
         [0.6605, 0.6343, 0.1809, 0.7287]],

        [[0.8958, 0.2787, 0.7523, 0.8852],
         [0.4710, 0.6392, 0.1260, 0.9431],
         [0.7909, 0.7231, 0.5006, 0.5039],
         [0.4290, 0.1759, 0.4063, 0.9533]]])

In [22]:
x = torch.rand(8, 8)
y = x.numpy()
type(y)

numpy.ndarray

In [23]:
x = torch.ones(1)
x.item()

1.0